//
// AWSConfiguration.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.4
//
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"IDENTITY_POOL_ID"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"ANALYTICS_APP_ID"
// CONTENT DELIVERY
#define AWS_CONTENT_MANAGER_S3_BUCKET_NAME @"S3_BUCKET_NAME"
#define AWS_CONTENT_MANAGER_CLOUD_FRONT_DOMAIN @"CLOUD_FRONT_DOMAIN"
#define AWS_CONTENT_MANAGER_CLOUD_FRONT_ORIGIN_S3 @"CLOUD_FRONT_ORIGIN_S3"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"MANAGER_S3_BUCKET_NAME"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"com.dancingqueen.walladog.ios"
