//
// AWSConfiguration.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.4
//
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:75e40b82-4207-413a-8f2c-9d5a6ac9f43c"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"08f1aa96b06f4601bfb57ed8bd21480c"
// CONTENT DELIVERY
#define AWS_CONTENT_MANAGER_S3_BUCKET_NAME @"walladog-contentdelivery-mobilehub-680575714"
#define AWS_CONTENT_MANAGER_CLOUD_FRONT_DOMAIN @"d1a2dfyas4tph4.cloudfront.net"
#define AWS_CONTENT_MANAGER_CLOUD_FRONT_ORIGIN_S3 @"walladog-contentdelivery-mobilehub-680575714"
// USER AGENT
#define AWS_MOBILEHUB_USER_AGENT @"MobileHub 32f4ea67-ad93-4efb-9a41-797bd3e0e43f aws-my-sample-app-ios-objc-v0.4"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"MANAGER_S3_BUCKET_NAME"
